#pragma once

#include <vector>
#include <string>

enum class SCRIPT_TYPE
{
	AISCRIPT,
	AMERAPLAYERMOVESCRIPT,
	ATTACKSTATESCRIPT,
	BACKGROUNDSCRIPT,
	BASICBALLSCRIPT,
	BOSSMONSTERSCRIPT,
	BUTTONSCRIPT,
	CAMERAMOVESCRIPT,
	CLOUDSCRIPT,
	CONSUMESCRIPT,
	CURSORSCRIPT,
	DAMAGESCRIPT,
	DEADSTATESCRIPT,
	DOUBLEJUMPSCRIPT,
	EXPSCRIPT,
	GRAVITYSCRIPT,
	GROUNDSCRIPT,
	HPSCRIPT,
	IDLESTATESCRIPT,
	INVENTORYSCRIPT,
	ITEMSCRIPT,
	LAUNCHSKILLSCRIPT,
	MAINBARSCRIPT,
	MISSILESCRIPT,
	MOBGROUNDSCRIPT,
	MONSTERFACTORYSCRIPT,
	MONSTERSCRIPT,
	MPSCRIPT,
	NUMBERSCRIPT,
	PAPERBURNSCRIPT,
	PATROLSTATESCRIPT,
	PLAYERSCRIPT,
	PORTALSCRIPT,
	RIGIDBODYSCRIPT,
	SCENESTARTSCRIPT,
	SKILLNEARSCRIPT,
	SKILLSCRIPT,
	STATESCRIPT,
	TRACESTATESCRIPT,
	WALLSCRIPT,
	END,
};

using namespace std;

class CScript;

class CScriptMgr
{
public:
	static void GetScriptInfo(vector<wstring>& _vec);
	static CScript * GetScript(const wstring& _strScriptName);
	static CScript * GetScript(UINT _iScriptType);
	static const wchar_t * GetScriptName(CScript * _pScript);
};
